napi port
RvD-Projects/electron-vue-vite-ts pull request #14
Opened 2022-11-06 22:09 UTC by wijiler

I think this is what you wanted?

2022-11-07 01:49 UTC, Izocel requested changes
- We cannot get rid of neon-preludes
- Why Removing Cargo.lock  and the pacakge.json ? (never do this its too early in the project)
- Were's the node and import of the created module into main.ts ?

2022-11-07 01:49 UTC, Izocel commented on rusties/cpu-count/Cargo.toml
> -features = ["napi-6"]
I think neon already uses napi ?

2022-11-07 01:49 UTC, Izocel commented on rusties/cpu-count/package.json
> -  "scripts": {
this was building a index.node

2022-11-07 01:49 UTC, Izocel commented on rusties/cpu-count/src/lib.rs
> -use neon::prelude::*;
Why removing the 2 fonction that i wanted to export ?

2022-11-10 01:55 UTC, wijiler commented on rusties/cpu-count/Cargo.toml
> -features = ["napi-6"]
didnt notice that

2022-11-10 01:57 UTC, wijiler commented
the node I deleted as I was just cleaning up and It must've gotten caught in the crossfire

2022-11-10 01:59 UTC, wijiler commented
will make changes later,but right now I have to focus on one of my projects

2022-11-10 03:09 UTC, Izocel commented
No problem i'll close it then you could do another PR if you wish

2022-11-10 03:09 UTC, closed without merging